url: "https://katsa9.github.io"
baseurl: ""

# Site settings
title: Kathleen Brand
email: your-email@domain.com
description: "This is my personal/portfolio site cv thing. Feel free to look around and get in touch. I am a full-stack developer passionate about UX and creating easy to maintain elegant applications."


# Team names, titles and social links
people:
- name: Kathleen Brand
  pic: 1
  position: Senior Software Engineer
  social:
    - title: twitter
      url: https://twitter.com/KathleenJBrand
    - title: github
      url: https://github.com/katsa9
    - title: linkedin
      url: https://www.linkedin.com/in/kathleen-j-brand
    - title: medium
      url: https://medium.com/@kathleen.brand2
  techskills: 
      - Java 
      - ReactJS
      - AngularJs
      - Typescript
      - Javascript
      - HTML
      - CSS 
      - SQL
      - Git
      - Balsamiq
      - Technical Writing
      - UX Design
      - Object Oriented Programming
      - Sketch
  softskills: 
      - Mentoring
      - Adaptability
      - Time Management
      - Creativity Skills
      - Teamwork

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/KathleenJBrand
  - title: github
    url: https://github.com/katsa9
  - title: medium
    url: https://medium.com/@kathleen.brand2

# Postal address (add as many lines as necessary)
address:
  - line: Cape Town
  - line: South Africa

# Build settings
markdown: kramdown
permalink: pretty

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
